name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - pip<=24.2
  - pip:
      - absl-py==2.2.2
      - alembic==1.16.1
      - astunparse==1.6.3
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - dagshub==0.5.1
      - docker==7.1.0
      - entrypoints==0.4
      - Flask==3.1.1
      - flatbuffers==25.2.10
      - fonttools==4.58.0
      - future==1.0.0
      - gast==0.6.0
      - gitdb==4.0.12
      - GitPython==3.1.44
      - google-auth==2.40.2
      - google-auth-oauthlib==1.2.2
      - google-pasta==0.2.0
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - greenlet==3.2.2
      - grpcio==1.71.0
      - h5py==3.13.0
      - hyperopt==0.2.7
      - idna==3.10
      - importlib_metadata==7.2.1
      - itsdangerous==2.2.0
      - Jinja2==3.1.6
      - joblib==1.5.1
      - keras==2.15.0
      - keras-tuner==1.4.7
      - kiwisolver==1.4.8
      - kt-legacy==1.0.5
      - libclang==18.1.1
      - Mako==1.3.10
      - Markdown==3.8
      - MarkupSafe==3.0.2
      - matplotlib==3.10.3
      - ml-dtypes==0.2.0
      - mlflow==2.19.0
      - networkx==3.4.2
      - numpy==2.2.1
      - oauthlib==3.2.2
      - opt_einsum==3.4.0
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.2.1
      - protobuf==4.25.7
      - psutil==5.9.0
      - py4j==0.10.9.9
      - pyarrow==15.0.2
      - pyasn1==0.6.1
      - pyasn1_modules==0.4.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pywin32==310
      - PyYAML==6.0.2
      - querystring-parser==1.2.4
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-learn==1.6.0
      - scipy==1.14.1
      - six==1.17.0
      - smmap==5.0.2
      - SQLAlchemy==2.0.41
      - sqlparse==0.5.3
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-intel==2.15.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tomli==2.2.1
      - tqdm==4.67.1
      - typing_extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.4.0
      - waitress==3.0.2
      - Werkzeug==3.1.3
      - wrapt==1.14.1
      - zipp==3.21.0
