name: MLflow CI Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  mlflow-train:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting MLflow training job..."

      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mlflow

      - name: Run mlflow project
        run: |
          cd MLProject
          mlflow run . \
            -P epochs=10 \
            -P batch_size=32 \
            -P learning_rate=0.001 \
            -P n_hidden=2 \
            -P n_units=64 \
            -P dropout_rate=0.3

      - name: Get latest MLflow run_id
        run: |
          echo "Getting latest MLflow run ID..."
          cd MLProject
          latest_run=$(ls -td mlruns/0/* | head -1 | xargs basename)
          echo "Latest run ID: $latest_run"
