name: MLflow Deep Learning CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MLProject/requirements.txt

      - name: Start MLflow Tracking Server (Docker container)
        run: |
          docker run -d -p 5000:5000 \
            -v ${{ github.workspace }}/MLProject/mlruns:/mlflow/mlruns \
            --name mlflow-server \
            ghcr.io/mlflow/mlflow:latest \
            mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns

      - name: Wait for MLflow server
        run: |
          for i in {1..30}; do
            if curl --silent http://127.0.0.1:5000/health; then
              echo "MLflow server is ready!"
              break
            fi
            echo "Waiting for MLflow server..."
            sleep 3
          done

      - name: Run training script
        env:
          MLFLOW_TRACKING_URI: http://127.0.0.1:5000
        run: |
          cd MLProject
          python modelling.py \
            --epochs 10 \
            --batch_size 32 \
            --learning_rate 0.001 \
            --n_hidden 2 \
            --n_units 64 \
            --dropout_rate 0.3

      - name: Stop MLflow server
        run: docker stop mlflow-server
